# Identifiants SonarCloud
sonar.projectKey=bob_frontend
sonar.organization=hafidaassendal
sonar.host.url=https://sonarcloud.io

# Répertoires
sonar.sources=src/app
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/coverage/**

# Couverture de code (lcov)
sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
sonar.typescript.lcov.reportPaths=coverage/bobapp/lcov.info

# Module JS/TS
sonar.sourceEncoding=UTF-8