#il va contenir deux job 
#job1 pour builder les images  front et backk uniquement pour l event pul request vers la branche main 
#un job pour pour pucher les image sur docker uniquement pour l event push 
