# job1 de test: step pour lancer les test +1 step pour souvgarder le rapport de  test sur le repo
# job2 sonar: va lancer sonar scanner le projet et publier le rapport sur sonarcub 

#ecouter  push et travailler sur la branche main 
# sonar 

on:
  push:
    branches: [ "feature/*", "release/*", "hotfix/*", "develop","main" ]
    paths: [ 'back/**', '.github/workflows/**' ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  tests-sonar:
    name: Backend - Tests & Coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('back/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run backend tests with JaCoCo
        run: mvn clean verify
        working-directory: back

      - name: Save test report
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: back/target/surefire-reports/

      - name: SonarCloud Scan - Back
        uses: SonarSource/sonarcloud-github-action@v3
        with:
         projectBaseDir: ./back
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN_BAKEND}}

